### ISSUE TITLE
[BUG] Status access violation error in the browser 

### ISSUE THREAD

**Issue by RobGrover** [raybellis/emu.tools-public#10]
**Describe the bug**
Status Access Violation Error in the browser when attempting to start E-Remote with either Studiomux or LoopMIDI applications running.

**To Reproduce**
Have either Studiomux or LoopMIDI programs running and start E-Remote.

**Expected behavior**
E-Remote to start without error.

**Screenshots**
![StatusAccessViolationError](https://user-images.githubusercontent.com/64709495/81241890-7f1b0400-9003-11ea-878e-0bf3ac49c20b.jpg)

**System Info**
- Sampler Model [E4 Platinum]
- EOS Version [/4.7]
- Host Computer OS/Version [Windows 6 Core Desktop PC/Windows 7 64 Bit]
- Browser/Version [Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)]
- MIDI Interface [Edirol UM-550]

For E-Remote:
- Does the app recognize all of your MIDI ports? [Yes when the Studiomux.exe and LoopMIDI.exe processes are stopped]
- Does the app recognize your sampler? [Yes but as an E4XT Ultra]
- Does the app mirror the display properly? [Yes when the Studiomux.exe and LoopMIDI.exe processes are stopped]

**Additional context**

**Comment by alfonso73** [comment]
Hi, probably is the same issue i have on my system (Win 10 64bit with LoopBE30)
Here's the issue #6 link

**Comment by raybellis** [comment]
It might be - are then any console log error messages generated (visible via the "developer tools" menu) ?

**Comment by RobGrover** [comment]
I’ll have a look at the developer tools menu next time I’m at my sampler and post any messages here.

**Comment by raybellis** [comment]
Thanks - I've also just added some error checking that may make the code more robust against devices being locked by other applications, so please try that too.

**Comment by RobGrover** [comment]
Hi, it still gives the error on startup if either app is running. Here is a copy of the log from the console after it has failed to start. 

[www.emu.tools-1588811872347.log](https://github.com/raybellis/emu.tools-public/files/4590130/www.emu.tools-1588811872347.log)

Also here is a copy of the log after both applications have been closed and  E-remote has started without error.

[www.emu.tools-1588812399171.log](https://github.com/raybellis/emu.tools-public/files/4590132/www.emu.tools-1588812399171.log)

Maybe you could add the option to select which midi ports E-Remote uses so that it can filter out this unnecessary information and doesn't look at these other ports/devices/applications. 

To be fair I can live with having to close these applications before starting E-Remote as I can start them afterwards and everything works okay.

**Comment by raybellis** [comment]
The scan process is the same as for e-loader (in fact it's the same code), and the intent is to make using the apps as idiot proof as possible :)

[that said, I'm considering how I might cache the scan results between sessions, and only do an automatic scan if I detect that the MIDI port configuration has changed]

If I read your first log correctly, it crashes at the very point at which it first opens your `Output-10` for the first time, that being the one that has your E-mu device on it.   This might suggest that even if I didn't use the scan method that a crash would happen if that device were opened manually by user selection.

Are the other two applications using any of the other MIDI ports `output-1` through `output-9`?   It's still odd that it's specifically output 10 on which it crashes.

Could you also please try the scan with those apps running but with the E-mu turned off?   That might help identify whether it's the scan itself that's causing the crash, or some part of the interaction with the E-mu when it's detected.

**Comment by RobGrover** [comment]
The other 2 apps are for me to use my iPad with the Lemur app as a bidirectional midi control surface over a wired (lightning) connection, they should have no connections to my Emu or any UM-550 ports. As far as I know they are just virtual ports that allow the iPad, Midimux and Lemur apps to communicate with my PC.

Here is another log with the Emu turned off, it crashed and show the status access violation error.

[www.emu.tools-1588877494392.log](https://github.com/raybellis/emu.tools-public/files/4595111/www.emu.tools-1588877494392.log)

**Comment by raybellis** [comment]
Thanks Rob - was that with those apps still running and did it crash?   I don't see the log ending when output-10 is opened like it did in your previous log, although it does perhaps end slightly prematurely (while polling output-14).

**Comment by RobGrover** [comment]
Yes the Emu was switched off, the UM-550 on, both apps were running and it crashed showing the status access violation error. I can run it again and upload another log in case something got missed off.

Edit: here is another log

[www.emu.tools-1588879687057.log](https://github.com/raybellis/emu.tools-public/files/4595276/www.emu.tools-1588879687057.log)

**Comment by RobGrover** [comment]
It seems the new option of selecting midi inputs and outputs has completely eliminated this issue for me.

**Comment by gmy77** [comment]
Windows 11 "latest update" + Microsoft Edge Ver. 119.0.2116.0 (Official Build) dev (64 bit)

Only happen in Github website, and at random appear "access violation error"... then i click to try another time and work.

This is the list of changes on "flags", i don't know if anything of these changes create this problem.

Enabled
Smooth Scrolling
Animate smoothly when scrolling page content. – Windows, Linux, Android

[#smooth-scrolling](edge://flags/#smooth-scrolling)

Enabled
Windows Fluent scrollbars.
Stylizes scrollbars with Microsoft Fluent design. – Windows

[#fluent-scrollbars](edge://flags/#fluent-scrollbars)

Enabled
Omnibox calc provider
When enabled, suggests recent calculator results in the omnibox. – Mac, Windows, Linux

[#omnibox-calc-provider](edge://flags/#omnibox-calc-provider)

Enabled
Parallel downloading
Enable parallel downloading to accelerate download speed. – Mac, Windows, Linux, Android

[#enable-parallel-downloading](edge://flags/#enable-parallel-downloading)

Enabled
Calculate window occlusion on Windows
Calculate window occlusion on Windows will be used in the future to throttle and potentially unload foreground tabs in occluded windows – Windows

[#calculate-native-win-occlusion](edge://flags/#calculate-native-win-occlusion)

Enabled
Automatic HTTPS
Enables support for Automatic HTTPS, which switches connections to websites from HTTP to HTTPS. The feature can then be turned on/off or further configured at edge://settings/privacy. – Mac, Windows, Linux, Android

[#edge-automatic-https](edge://flags/#edge-automatic-https)

Enabled
Project Kodiak: Terminology
Experience the new terminology for browser. – Mac, Windows, Linux

[#edge-project-kodiak](edge://flags/#edge-project-kodiak)

Enabled
Project Kodiak: Look and Feel
Experience the new work and personal browser asthetic changes. – Mac, Windows, Linux

[#edge-project-kodiak-look-and-feel](edge://flags/#edge-project-kodiak-look-and-feel)

Enabled
Project Kodiak: Policy Filter
A lightly managed personal browser that lets you access your favorite sites and services without compromising your organization's security and compliance. – Mac, Windows, Linux

[#edge-project-kodiak-policy-filter](edge://flags/#edge-project-kodiak-policy-filter)

Enabled
Microsoft Edge Reading View
Enables Reading view in Microsoft Edge – Mac, Windows, Linux

[#edge-reading-view](edge://flags/#edge-reading-view)

Enabled
Project Robin experiment
If enabled, Project Robin features are enabled. – Mac, Windows, Linux, Android

[#edge-robin](edge://flags/#edge-robin)

Enabled
Enable Data Loss Prevention SaaS Experimentation
If enabled, a select list of sites will have Data Loss Prevention leak controls applied. – Mac, Windows, Linux

[#edge-saas-dlp](edge://flags/#edge-saas-dlp)

Enabled
Microsoft Edge Screenshot
Enables the feature-rich, easily accessible screenshot feature. – Mac, Windows

[#edge-screenshot](edge://flags/#edge-screenshot)

Enabled
Microsoft Edge rounded corners
Enables rounded tabs, rounded corners around browser frames that bring visual separation – Mac, Windows, Linux

[#edge-rounded-containers](edge://flags/#edge-rounded-containers)

Enabled
Microsoft Edge profile icon in title bar
Moves the profile icon to title bar – Mac, Windows, Linux

[#edge-minimal-toolbar](edge://flags/#edge-minimal-toolbar)

Enabled
Make Rounded Tabs feature available
Enables an appearance setting to use rounded corners for browser tabs. This option can then be turned on/off at edge://settings/appearance. – Mac, Windows, Linux

[#edge-visual-rejuv-rounded-tabs](edge://flags/#edge-visual-rejuv-rounded-tabs)

Enabled
Enable Workspaces
Enables Microsoft Edge Workspaces for preview eligible users. – Mac, Windows, Linux

[#edge-workspaces](edge://flags/#edge-workspaces)

Enabled
Enable Workspaces Comments
Enables comments in Microsoft Edge workspaces. – Mac, Windows, Linux

[#edge-workspaces-comments](edge://flags/#edge-workspaces-comments)

Enabled
Enhance text contrast
Renders text using the same contrast and gamma settings that are used elsewhere in Windows. Run the ClearType Text Tuner to adjust the contrast and gamma settings for your monitor. – Windows

[#edge-enhance-text-contrast](edge://flags/#edge-enhance-text-contrast)

Enabled
Windows Fluent overlay scrollbars.
To experiment with Fluent overlay scrollbars, enable this feature and turn “Always Show Scrollbars” setting off in Settings > Appearance > Customize browser. – Windows

[#edge-overlay-scrollbars-win-style](edge://flags/#edge-overlay-scrollbars-win-style)

Enabled
Enable Windows 11 Acrylic effect in menus
Enables support for the Acrylic effect in menus, if it is available on the system. Requires Windows 11 or later. – Windows

[#edge-visual-rejuv-materials-menu](edge://flags/#edge-visual-rejuv-materials-menu)
