### ISSUE TITLE
[BUG] certificate expired on emu.tools page

### ISSUE THREAD

**Issue by ncapone** [raybellis/emu.tools-public#16]
**Describe the bug**
The certificate for the emu.tools web application is expired on 23/11/2024 which throws a security warning and renders the page unusable
**To Reproduce**
Open emu.tools and navigate to any of the features. 

**Expected behavior**
The tools working as expected

**Screenshots**

**System Info**
E-Mu e6400 Ultra
- EOS Version 4.10
- Mac OS X 13.5
- Chrome 131.0.6778.86
- Squarp Pyramid 
For E-Remote:
- Does the app recognize all of your MIDI ports? 
- Does the app recognize your sampler? [Yes/No]
- Does the app mirror the display properly? [Yes/No]

**Additional context**

**Comment by raybellis** [comment]
thanks for the heads up - this is resolved now!

(the certificate had been renewed, but Apache hadn't been restarted so hadn't picked it up)
