### ISSUE TITLE
Clickable soft buttons

### ISSUE THREAD

**Issue by raybellis** [raybellis/emu.tools-public#4]
Accept click events from the areas on the LCD that represent soft buttons.

**Comment by encoderaudio** [comment]
That would be amazing!
Also, support for "virtual ASCII keyboard port" ?
Like, when you type the preset/patch names.

**Comment by raybellis** [comment]
soft LCD buttons implemented in 501f0f68caee0f307fcb70fe6cfa1518753bd572
