### ISSUE TITLE
[BUG] Reflect sampler changes on the remote

### ISSUE THREAD

**Issue by BeyondBuka** [raybellis/emu.tools-public#7]
**Describe the bug**
Moving controls on the remote is reflected on the sampler but not the other way around and instantly. Only after changing something on the remote does the change from the sampler gets noticed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Info**
- Sampler [E4XT ultra]
- EOS Version [4.7]
- Host Computer OS/Version win7-64bit
- Browser/Version latest Chrome
- MIDI Interface novation x-station

For E-Remote:
- Does the app recognize all of your MIDI ports? [Yes]
- Does the app recognize your sampler? [Yes]
- Does the app mirror the display properly? [Yes]

**Additional context**

**Comment by raybellis** [comment]
Resolved by e387a433df0e13be1fd81ed55bd9f92fcb7f0342
